# Generated by paninfraspec-gen. Customise via environment, not in-place.
require 'serverspec'

if ENV['TARGET_HOST'].nil? || ENV['TARGET_HOST'].empty?
  set :backend, :exec
else
  require 'net/ssh'
  set :backend, :ssh
  set :host, ENV['TARGET_HOST']
  set :ssh_options, Net::SSH::Config.for(ENV['TARGET_HOST'])
  set :request_pty, true
end

RSpec.configure do |c|
  c.color    = true
  c.formatter = :documentation
end
