# Generated by paninfraspec-gen — ansible_spec harness.
# Connection details are pulled from the Ansible inventory via
# AnsibleSpec.get_properties; the Rakefile sets TARGET_HOST per task.
require 'serverspec'
require 'ansible_spec'
require 'net/ssh'

set :backend, :ssh
set :request_pty, true

host = ENV['TARGET_HOST']
if host && !host.empty?
  options = Net::SSH::Config.for(host)
  options[:user] ||= ENV['SSH_USER'] || ENV['USER']
  set :host,        host
  set :ssh_options, options
end

RSpec.configure do |c|
  c.color    = true
  c.formatter = :documentation
end
