module PanInfraSpec.Scaffold
  ( OutputFile (..)
  , BuiltinDeriver (..)
  , Scaffold (..)
  , defaultServerspecScaffold
  , loadScaffold
  , resolveBuiltinDerivers
  , renderAnsibleHostsIni
  , renderAnsibleSiteYml
  ) where

import Control.Exception (IOException, try)
import Data.List (nub)
import Data.Text (Text)
import qualified Data.Text as T
import qualified Dhall

import PanInfraSpec.IR (Node (..), Role (..))

-- | A single file emitted alongside the per-host spec files. Mirrors the
-- Dhall record @{ path : Text, content : Text }@ in @dhall/Scaffold.dhall@.
data OutputFile = OutputFile
  { ofPath    :: Text
  , ofContent :: Text
  }
  deriving stock (Show, Eq)

instance Dhall.FromDhall OutputFile where
  autoWith _ = Dhall.record $
    OutputFile
      <$> Dhall.field "path"    Dhall.auto
      <*> Dhall.field "content" Dhall.auto

-- | Shipped, Haskell-rendered derivers. The Dhall side carries only the
-- target path; the actual file content is computed in Haskell from the
-- per-job node list at emit time. See 'resolveBuiltinDerivers'.
data BuiltinDeriver
  = AnsibleHostsIni Text
  | AnsibleSiteYml  Text
  deriving stock (Show, Eq)

instance Dhall.FromDhall BuiltinDeriver where
  autoWith _ = Dhall.union
    (  (AnsibleHostsIni <$> Dhall.constructor "AnsibleHostsIni" pathRecord)
    <> (AnsibleSiteYml  <$> Dhall.constructor "AnsibleSiteYml"  pathRecord)
    )
    where
      pathRecord = Dhall.record (Dhall.field "path" Dhall.auto)

-- | Execution scaffold loaded from a Dhall file (or supplied as the built-in
-- 'defaultServerspecScaffold'). The scaffold owns the auxiliary files that
-- wrap the per-host spec files so a runner (Serverspec, ansible_spec, ...)
-- can pick them up.
--
-- 'sStaticFiles' are inventory-independent files (Rakefile / spec_helper.rb
-- in the Serverspec case). 'sDerivedFiles' is a Dhall function applied to
-- the resolved inventory at emit time so the scaffold can compute auxiliary
-- files (ansible_spec's @hosts@ and @site.yml@) from the node list.
--
-- 'sBuiltinDerivers' is the escape hatch for derivations that are awkward
-- to express in Dhall (e.g. the role-name de-duplication needed for an
-- Ansible INI inventory). Each entry is rendered in Haskell; see
-- 'resolveBuiltinDerivers'.
--
-- Backend-specific vocabulary (the fact that Serverspec wants a Rakefile,
-- that a future InSpec scaffold would want its own profile layout, ...)
-- lives in the shipped Dhall scaffold preludes under @dhall/Scaffold/@, not
-- in this Haskell type.
data Scaffold = Scaffold
  { sName            :: Text
  , sStaticFiles     :: [OutputFile]
  , sDerivedFiles    :: [Node] -> [OutputFile]
  , sBuiltinDerivers :: [BuiltinDeriver]
  }

instance Dhall.FromDhall Scaffold where
  autoWith _ = Dhall.record $
    Scaffold
      <$> Dhall.field "name"         Dhall.auto
      <*> Dhall.field "staticFiles"  Dhall.auto
      <*> Dhall.field "derivedFiles"
            (Dhall.function (Dhall.inject :: Dhall.Encoder [Node]) Dhall.auto)
      <*> Dhall.field "builtinDerivers"     Dhall.auto

-- | The built-in Serverspec scaffold. Used when @--scaffold@ is omitted so
-- the pre-Scaffold-feature output stays bit-for-bit identical. The shipped
-- @dhall/Scaffold/Serverspec.dhall@ is kept in lockstep with this value
-- (verified by golden test).
defaultServerspecScaffold :: Scaffold
defaultServerspecScaffold = Scaffold
  { sName            = "serverspec"
  , sStaticFiles     =
      [ OutputFile { ofPath = "Rakefile",       ofContent = rakefileContent     }
      , OutputFile { ofPath = "spec_helper.rb", ofContent = specHelperContent   }
      ]
  , sDerivedFiles    = const []
  , sBuiltinDerivers = []
  }
  where
    specHelperContent = T.unlines
      [ "# Generated by paninfraspec-gen. Customise via environment, not in-place."
      , "require 'serverspec'"
      , ""
      , "if ENV['TARGET_HOST'].nil? || ENV['TARGET_HOST'].empty?"
      , "  set :backend, :exec"
      , "else"
      , "  require 'net/ssh'"
      , "  set :backend, :ssh"
      , "  set :host, ENV['TARGET_HOST']"
      , "  set :ssh_options, Net::SSH::Config.for(ENV['TARGET_HOST'])"
      , "  set :request_pty, true"
      , "end"
      , ""
      , "RSpec.configure do |c|"
      , "  c.color    = true"
      , "  c.formatter = :documentation"
      , "end"
      ]
    rakefileContent = T.unlines
      [ "# Generated by paninfraspec-gen."
      , "require 'rake'"
      , "require 'rspec/core/rake_task'"
      , ""
      , "specs = Rake::FileList['*_spec.rb']"
      , ""
      , "if specs.empty?"
      , "  abort 'no *_spec.rb files found in this directory'"
      , "end"
      , ""
      , "RSpec::Core::RakeTask.new(:spec) do |t|"
      , "  t.pattern    = specs"
      , "  t.rspec_opts = '--format documentation --color'"
      , "end"
      , ""
      , "task default: :spec"
      ]

-- | Load a 'Scaffold' from a Dhall file. IO failures (file missing, Dhall
-- type error) are returned as 'Left' so the CLI can surface them with a
-- consistent exit code.
loadScaffold :: FilePath -> IO (Either Text Scaffold)
loadScaffold path = do
  res <- try @IOException (Dhall.inputFile Dhall.auto path)
  pure $ case res of
    Right s -> Right s
    Left  e -> Left (T.pack (show e))

-- | Convert the scaffold's 'BuiltinDeriver' list into 'OutputFile' values
-- by running the Haskell-side renderers against the supplied node list.
resolveBuiltinDerivers :: [Node] -> [BuiltinDeriver] -> [OutputFile]
resolveBuiltinDerivers nodes = map go
  where
    go (AnsibleHostsIni p) = OutputFile p (renderAnsibleHostsIni nodes)
    go (AnsibleSiteYml  p) = OutputFile p (renderAnsibleSiteYml  nodes)

-- | Render an Ansible INI inventory grouped by 'Role'. One @[role]@ section
-- per distinct role (preserving first-seen order), one hostname per line.
-- Sections are separated by a single blank line; the file ends with a
-- trailing newline.
renderAnsibleHostsIni :: [Node] -> Text
renderAnsibleHostsIni nodes =
  T.intercalate "\n" (map section roles) <> "\n"
  where
    roles = nub (map (unRole . role) nodes)
    section r =
      let hosts = [ hostname n | n <- nodes, unRole (role n) == r ]
      in  "[" <> r <> "]\n" <> T.intercalate "\n" hosts <> "\n"

-- | Render a minimal Ansible site.yml: one @- hosts: <role>@ entry per
-- distinct role with an empty @roles:@ list. The shipped ansible_spec
-- Rakefile globs spec files directly per group, so the playbook only needs
-- to surface the group name.
renderAnsibleSiteYml :: [Node] -> Text
renderAnsibleSiteYml nodes =
  T.concat (map entry roles)
  where
    roles = nub (map (unRole . role) nodes)
    entry r = "- hosts: " <> r <> "\n  roles: []\n"
