module PanInfraSpec.Scaffold.Defaults.Serverspec
  ( defaultServerspecScaffold
  ) where

import qualified Data.Text as T

import PanInfraSpec.Scaffold (OutputFile (..), Scaffold (..))

-- | The built-in Serverspec scaffold. Used when @--scaffold@ is omitted so
-- the pre-Scaffold-feature output stays bit-for-bit identical. The shipped
-- @dhall/Scaffold/Serverspec.dhall@ is kept in lockstep with this value
-- (verified by golden test).
--
-- Each backend ships its default under @PanInfraSpec.Scaffold.Defaults.<Backend>@
-- so that 'PanInfraSpec.Scaffold' itself stays backend-agnostic.
defaultServerspecScaffold :: Scaffold
defaultServerspecScaffold = Scaffold
  { sName            = "serverspec"
  , sStaticFiles     =
      [ OutputFile { ofPath = "Rakefile",       ofContent = rakefileContent     }
      , OutputFile { ofPath = "spec_helper.rb", ofContent = specHelperContent   }
      ]
  , sDerivedFiles    = const []
  , sBuiltinDerivers = []
  }
  where
    specHelperContent = T.unlines
      [ "# Generated by paninfraspec-gen. Customise via environment, not in-place."
      , "require 'serverspec'"
      , ""
      , "if ENV['TARGET_HOST'].nil? || ENV['TARGET_HOST'].empty?"
      , "  set :backend, :exec"
      , "else"
      , "  require 'net/ssh'"
      , "  set :backend, :ssh"
      , "  set :host, ENV['TARGET_HOST']"
      , "  set :ssh_options, Net::SSH::Config.for(ENV['TARGET_HOST'])"
      , "  set :request_pty, true"
      , "end"
      , ""
      , "RSpec.configure do |c|"
      , "  c.color    = true"
      , "  c.formatter = :documentation"
      , "end"
      ]
    rakefileContent = T.unlines
      [ "# Generated by paninfraspec-gen."
      , "require 'rake'"
      , "require 'rspec/core/rake_task'"
      , ""
      , "specs = Rake::FileList['*_spec.rb']"
      , ""
      , "if specs.empty?"
      , "  abort 'no *_spec.rb files found in this directory'"
      , "end"
      , ""
      , "RSpec::Core::RakeTask.new(:spec) do |t|"
      , "  t.pattern    = specs"
      , "  t.rspec_opts = '--format documentation --color'"
      , "end"
      , ""
      , "task default: :spec"
      ]
